[features]
seeds = false
skip-lint = false
[programs.localnet]
p2p_nft_lending = "3ec8LhLQPbkQAgKL9mfC5zafoxiKe94DwnbDNrbsTHgA"



[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "/Users/m1/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
